# Generated by Django 5.2.4 on 2025-08-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='months',
            field=models.CharField(default=0.0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to='presentation'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='category',
            field=models.CharField(choices=[('Regular', 'Regular Trainee'), ('SIWES', 'SIWES Intern'), ('Extern', 'Extern'), ('Triptern', 'Triptern'), ('Bootcamp', 'Bootcamp Kid')], default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainee',
            name='payment_option',
            field=models.CharField(choices=[('Full Payment', 'Full Payment'), ('70% upfront and 30% later', '70% upfront and 30% later'), ('Monthly Payment', 'Monthly Payment')], default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='feedbacktrainer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fix_class',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationtrainer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='presentation_report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('level', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roothub_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevelTrainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roothub_app.courses')),
                ('trainer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roothub_app.trainers')),
                ('level_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roothub_app.level')),
            ],
        ),
    ]
