# Generated by Django 5.2.4 on 2025-08-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='account_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='birthday',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
