# Generated by Django 5.2.4 on 2025-08-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0003_alter_trainee_address_alter_trainee_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerCourseAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.courses')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.level')),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.trainers')),
            ],
        ),
    ]
