# Generated by Django 5.2.4 on 2025-08-20 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0004_trainercourseassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeCourseAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.courses')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.level')),
                ('trainee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.trainee')),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.trainers')),
            ],
        ),
    ]
