# Generated by Django 5.2.4 on 2025-08-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0005_traineecourseassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Trainers', 'Trainers'), ('Trainees', 'Trainees'), ('Course', 'Course')], default='General', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roothub_app.courses'),
        ),
    ]
