# Generated by Django 5.1.6 on 2025-04-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0006_alter_presentation_id_alter_presentation_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presentation_report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presentation_report',
            name='trainee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.trainee'),
        ),
    ]
