# Generated by Django 5.2.4 on 2025-08-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0006_announcement_category_announcement_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='number_of_presentation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
