# Generated by Django 5.2.4 on 2025-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0007_courses_number_of_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (4, 'Sub Admin'), (2, 'Trainer'), (3, 'Trainee')], default=1, max_length=50),
        ),
    ]
