# Generated by Django 5.1.6 on 2025-05-17 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0007_alter_assignment_id_alter_paymenttransaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainees', to='roothub_app.courses'),
        ),
    ]
