# Generated by Django 5.2.4 on 2025-08-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
