# Generated by Django 5.1.6 on 2025-05-18 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0008_alter_trainee_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='roothub_app.courses'),
        ),
    ]
