# Generated by Django 5.1.6 on 2025-05-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0009_alter_trainee_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fix_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=150)),
                ('class_date', models.DateTimeField(auto_now_add=True)),
                ('start_class', models.DateTimeField(auto_now_add=True)),
                ('end_class', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.courses')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.trainers')),
            ],
        ),
    ]
