# Generated by Django 5.1.2 on 2025-09-04 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0010_subadmin_remove_feedbackstudent_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('commission_rate', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount_paid', models.CharField(max_length=255)),
                ('installmental_payment', models.CharField(max_length=255)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Card')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorPayroll',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('total_salary', models.CharField(max_length=255)),
                ('amount_paid', models.CharField(max_length=255)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseleveltrainer',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='courseleveltrainer',
            name='level_id',
        ),
        migrations.RemoveField(
            model_name='courseleveltrainer',
            name='trainer_id',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='date_of_payment',
        ),
        migrations.AddField(
            model_name='courses',
            name='level_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roothub_app.level'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_assignment', to='roothub_app.traineecourseassignment'),
        ),
        migrations.AddField(
            model_name='trainers',
            name='commission_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainers',
            name='trainer_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignment', to='roothub_app.trainercourseassignment'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='roothub_app.courses'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='course_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainers', to='roothub_app.courses'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='roothub_app.courses'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='roothub_app.trainee'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='paymenthistory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='roothub_app.paymenthistory'),
        ),
        migrations.AddField(
            model_name='tutorpayroll',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='roothub_app.trainers'),
        ),
        migrations.DeleteModel(
            name='CourseLevelTrainer',
        ),
    ]
