# Generated by Django 5.1.6 on 2025-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0010_fix_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix_class',
            name='class_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fix_class',
            name='end_class',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fix_class',
            name='start_class',
            field=models.DateTimeField(),
        ),
    ]
