# Generated by Django 5.1.2 on 2025-09-04 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0011_payment_paymenthistory_tutorpayroll_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutorPayroll',
            new_name='TrainerPayroll',
        ),
        migrations.AddField(
            model_name='trainers',
            name='trainer_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_payroll', to='roothub_app.trainerpayroll'),
        ),
    ]
