# Generated by Django 5.1.6 on 2025-05-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0011_alter_fix_class_class_date_alter_fix_class_end_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix_class',
            name='class_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fix_class',
            name='end_class',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='fix_class',
            name='start_class',
            field=models.TimeField(),
        ),
    ]
