# Generated by Django 5.1.2 on 2025-09-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0012_rename_tutorpayroll_trainerpayroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='upfront_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='trainees', to='roothub_app.level'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='portion_type',
            field=models.CharField(blank=True, choices=[('Full Course', 'Full Course'), ('Level', 'Level')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='portion_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
