# Generated by Django 5.1.6 on 2025-05-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0012_alter_fix_class_class_date_alter_fix_class_end_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix_class',
            name='description',
            field=models.TextField(),
        ),
    ]
