# Generated by Django 5.1.2 on 2025-09-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0013_paymenthistory_upfront_due_date_trainee_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='course_id',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='roothub_app.courses'),
        ),
    ]
