# Generated by Django 5.2.4 on 2025-10-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0014_alter_trainers_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('70% upfront and 30% later', '70% upfront and 30% later'), ('Monthly Payment', 'Monthly Payment')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainee',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainee',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
