# Generated by Django 5.2.4 on 2025-10-16 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0015_paymenthistory_payment_option_trainee_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='levels',
        ),
        migrations.AddField(
            model_name='trainee',
            name='levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='roothub_app.level'),
        ),
    ]
