# Generated by Django 5.2.4 on 2025-10-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0016_remove_trainee_levels_trainee_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='levels',
        ),
        migrations.AddField(
            model_name='trainee',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='trainees', to='roothub_app.level'),
        ),
    ]
