# Generated by Django 5.2.4 on 2025-10-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0017_remove_trainee_levels_trainee_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillExpertise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Expertise',
            },
        ),
        migrations.RemoveField(
            model_name='trainers',
            name='competent_skills',
        ),
        migrations.RemoveField(
            model_name='trainers',
            name='skill_expertise',
        ),
        migrations.CreateModel(
            name='CompetentSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('skill_expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competent_skills', to='roothub_app.skillexpertise')),
            ],
            options={
                'unique_together': {('name', 'skill_expertise')},
            },
        ),
        migrations.AddField(
            model_name='trainers',
            name='competent_skills',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='roothub_app.competentskill'),
        ),
        migrations.AddField(
            model_name='trainers',
            name='skill_expertise',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='roothub_app.skillexpertise'),
        ),
    ]
