# Generated by Django 5.2.4 on 2025-10-29 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0018_skillexpertise_remove_trainers_competent_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='expected_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerpayroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainerpayroll',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Bank Transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='trainerpayroll',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerpayroll',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_trainer_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerpayroll',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainerpayroll',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
