# Generated by Django 5.2.4 on 2025-11-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0020_assignmentsubmission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='competent_skills',
            field=models.ManyToManyField(blank=True, related_name='competent_skills', to='roothub_app.competentskill'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='skill_expertise',
            field=models.ManyToManyField(blank=True, related_name='skill_expertise', to='roothub_app.skillexpertise'),
        ),
    ]
