# Generated by Django 5.2.4 on 2025-11-12 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0021_alter_trainers_competent_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Announcement expiry date', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='notification_clicked',
            field=models.ManyToManyField(blank=True, related_name='clicked_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Schedule announcement for future delivery', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_admins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_courses',
            field=models.ManyToManyField(blank=True, related_name='targeted_announcements', to='roothub_app.courses'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_trainees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_trainers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Trainers', 'Trainers'), ('Trainees', 'Trainees'), ('Course', 'Course'), ('Multi-Category', 'Multi-Category')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='curriculum')),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.trainers')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('badge_dismissed', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
