# Generated by Django 5.2.4 on 2025-11-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0022_announcement_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PresentationSubmit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('link', models.CharField()),
                ('file', models.FileField(blank=True, null=True, upload_to='presentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('presentation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.presentation')),
                ('trainee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roothub_app.trainee')),
            ],
        ),
    ]
