# Generated by Django 5.2.4 on 2025-11-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0023_assignment_remark_presentationsubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationsubmit',
            name='link',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentationsubmit',
            name='presentation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roothub_app.presentation'),
        ),
        migrations.AlterField(
            model_name='presentationsubmit',
            name='trainee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roothub_app.trainee'),
        ),
    ]
