# Generated by Django 5.2.4 on 2025-11-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roothub_app', '0024_alter_presentationsubmit_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('reminder_days', models.IntegerField(choices=[(1, '1 day'), (3, '3 days'), (7, '7 days'), (14, '14 days')], default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='roothub_app.trainee')),
            ],
        ),
    ]
